### PR TITLE
Remove link to broken website

### LINKED ISSUE #5: website offline?
The website linked in the README seems to have been domain squatted or hacked. Please remove the site from README, so other people don't accidentally click.

Also, consider using a static site host, such as [Neocities](https://neocities.org/) or GitHub pages, for the game website.

### PR DESCRIPTION
**Pull request by brylie**
Closes #5

### CODE REVIEW

**Comment by bojidar-bg** [comment]
Thanks for noticing!

**Comment by brylie** [comment]
YW. Is the Kobuge project still active? I have a couple of games that might be good candidates for incubation.

**Comment by brylie** [comment]
By the way, Namecheap has a [sale this week on **.gg** domains](https://www.namecheap.com/domains/registration/cctld/gg.aspx). So, you might be able to get *kobuge(dot)gg*

**Comment by ObaniGemini** [comment]
KOBUGE itself still is alive, but I don't think any of its members is still active on one of our projects

**Comment by ObaniGemini** [comment]
By the way KOBUGE is an organization of people, not a "project" as you call it

**Comment by brylie** [comment]
Cool, I was just checking if KOBUGE was active any longer. How is the organization run? Are there meetings or any communications channels?

**Comment by fry-** [comment]
hey @brylie ! We are basically a bunch of guys hanging around in the channel #kobuge on irc.freenode.
And yeah, we are kinda active in the channel taking with each other, but currently everybody is occupied with something else than making a game together, so no actively developed project (sadly).

Please feel free to join the channel and push your ideas towards a new group project! It just shouldn't be too complicated and kinda thought out, because both these factors were the death-sentence for most of our started (and abandoned) games :smile:

**Pull request merged**
